### ISSUE TITLE
Not able to delete application group

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/FilterManager#79]
![image](https://user-images.githubusercontent.com/7513273/36358424-d4d4d310-14d3-11e8-8783-bbeea2f538f8.png)

**Comment by bluesven869** [comment]
It's working on my side.
Please let me know what exactly does not run.

**Comment by montesound** [comment]
I see that now. I'm not able to delete groups on the production system but I can on the test system. Is this somehow related to #77?

**Comment by bluesven869** [comment]
OK

I will check it on prod server.
can you let me know the credentials of prod server?

**Comment by dkwiebe** [comment]
@montesound I've been testing this a little bit and it looks like this is because the app group is tied to a setting group already.

@bluesven869 This is what's causing it to fail.  It would work if we had a check built in.
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`citadel`.`user_group_to_app_groups`, CONSTRAINT `user_group_to_app_groups_app_group_id_foreign` FOREIGN KEY (`app_group_id`) REFERENCES `app_groups` (`id`)) (SQL: delete from `app_groups` where `id` = 29)

**Comment by bluesven869** [comment]
@dkwiebe 
Hoping to give me a access to prod server.
I think there are some issues in database

**Comment by montesound** [comment]
@dkwiebe You are correct. I am now able to delete application groups if I remove them from the settings group first. I'm thinking it would still be good to build a check in if it isn't too hard.

**Comment by bluesven869** [comment]
@dkwiebe  I found the issue what's wrong.
so I fixed it and created PR.
Please check it and hope to merge.

**Comment by dkwiebe** [comment]
@montesound when you have time can you check this?

**Comment by montesound** [comment]
This appears to be fixed. Thanks!
